name = "ParametricSchematics"
uuid = "438a115d-bc86-471c-afd0-3ed3084b72e0"
version = "0.0.0-DEV"
authors = ["Ellie <intricatebread@gmail.com> and contributors"]

[deps]
Litematica = "82944276-add8-4074-9c50-3a921b02611b"
MinecraftDataStructures = "c8cd69f1-bc5f-4dbb-a861-15a5a68cdaf9"
NBT = "b6fc1ac1-9d30-4df3-aa0b-dd666eb91533"
PooledArrays = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"

[compat]
Litematica = "0.1.0"
MinecraftDataStructures = "1.0.0"
NBT = "1.0.0"
PooledArrays = "1.4.3"
julia = "1.11"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "JET", "Test"]
